name: Threat Agent Simulator

on:
  push:
    branches:
      - main

jobs:
  run-threat-agent:
    runs-on: ubuntu-latest
    env:
      VM_IP_ADDRESS: ${{ secrets.Victim_IP_ADDR }}
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Threat Agent Script
      run: |
        chmod +x ./threat_agent.sh
        ./threat_agent.sh
